/**
 * E2E Dev Server Wrapper
 *
 * Starts a PostgreSQL Testcontainer, runs migrations and seeds,
 * writes .env.test, then starts the Next.js dev server.
 *
 * This script is used as the Playwright webServer command because
 * Playwright starts webServer BEFORE globalSetup. By running the
 * Testcontainer setup here, we ensure DATABASE_URL is available
 * when Next.js compiles.
 *
 * Cleanup (container stop, .env.test removal) happens when
 * Playwright sends SIGTERM to this process after tests complete.
 */

import { PostgreSqlContainer } from "@testcontainers/postgresql";
import type { StartedPostgreSqlContainer } from "@testcontainers/postgresql";
import { execSync, spawn } from "node:child_process";
import { writeFileSync, unlinkSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ENV_TEST_FILE = resolve(process.cwd(), ".env.test");

let container: StartedPostgreSqlContainer;

async function main() {
  console.log("\n🧪 E2E Dev Server");
  console.log("   Starting PostgreSQL Testcontainer...\n");

  container = await new PostgreSqlContainer("postgres:17-alpine").start();
  const connectionString = container.getConnectionUri();

  // Write .env.test so globalSetup can load DATABASE_URL for the Playwright process
  writeFileSync(
    ENV_TEST_FILE,
    `# Auto-generated by e2e/dev-server.ts — DO NOT COMMIT\nDATABASE_URL="${connectionString}"\n`
  );

  const env = { ...process.env, DATABASE_URL: connectionString };

  // Run migrations
  console.log("   Running migrations...\n");
  execSync("pnpm db:migrate:all", { cwd: process.cwd(), stdio: "inherit", env });

  // Seed test data
  console.log("\n   Seeding database...\n");
  execSync("pnpm db:seed", { cwd: process.cwd(), stdio: "inherit", env });

  console.log("\n✅ Testcontainer ready — starting Next.js dev server\n");

  // Start Next.js dev server (inherits DATABASE_URL via env)
  const child = spawn("pnpm", ["dev"], { env, stdio: "inherit" });

  child.on("exit", (code) => {
    if (code !== null && code !== 0) {
      console.error(`Next.js dev server exited with code ${code}`);
    }
  });

  // Cleanup on termination (Playwright sends SIGTERM after tests)
  const cleanup = async () => {
    console.log("\n🧹 E2E Cleanup");
    child.kill();
    console.log("   Stopping Testcontainer...");
    await container.stop();
    if (existsSync(ENV_TEST_FILE)) {
      unlinkSync(ENV_TEST_FILE);
    }
    console.log("✅ E2E cleanup complete\n");
    process.exit(0);
  };

  process.on("SIGTERM", cleanup);
  process.on("SIGINT", cleanup);
}

main().catch((err) => {
  console.error("❌ E2E dev server failed:", err);
  process.exit(1);
});
