/**
 * Playwright Global Setup
 *
 * Starts a PostgreSQL Testcontainer and prepares it for E2E tests.
 * The container is created BEFORE the webServer starts, ensuring
 * DATABASE_URL is available when Next.js compiles.
 *
 * Returns a teardown function that stops the container after all tests.
 */

import { PostgreSqlContainer } from "@testcontainers/postgresql";
import { execSync } from "node:child_process";
import { writeFileSync, unlinkSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ENV_TEST_FILE = resolve(process.cwd(), ".env.test");

async function globalSetup() {
  console.log("\n🧪 E2E Global Setup");
  console.log("   Starting PostgreSQL Testcontainer...\n");

  const container = await new PostgreSqlContainer("postgres:17-alpine").start();
  const connectionString = container.getConnectionUri();

  // Write .env.test for the webServer child process (Next.js dev)
  writeFileSync(
    ENV_TEST_FILE,
    `# Auto-generated by e2e/global-setup.ts — DO NOT COMMIT\nDATABASE_URL="${connectionString}"\n`
  );

  // Set for the Playwright process itself
  process.env.DATABASE_URL = connectionString;

  // Run migrations
  console.log("   Running migrations...\n");
  execSync("pnpm db:migrate:all", {
    cwd: process.cwd(),
    stdio: "inherit",
    env: { ...process.env, DATABASE_URL: connectionString },
  });

  // Seed test data
  console.log("\n   Seeding database...\n");
  execSync("pnpm db:seed", {
    cwd: process.cwd(),
    stdio: "inherit",
    env: { ...process.env, DATABASE_URL: connectionString },
  });

  console.log("\n✅ Testcontainer ready for E2E tests\n");

  // Return teardown function (Playwright 1.31+)
  return async () => {
    console.log("\n🧹 E2E Teardown");
    console.log("   Stopping Testcontainer...\n");
    await container.stop();
    if (existsSync(ENV_TEST_FILE)) {
      unlinkSync(ENV_TEST_FILE);
    }
    console.log("✅ E2E cleanup complete\n");
  };
}

export default globalSetup;
